//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//


package lt.atea.vaiisis.authentication.model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticationProvider.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="authenticationProvider">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="auth.login.pass"/>
 *     &lt;enumeration value="auth.lt.identity.card"/>
 *     &lt;enumeration value="auth.lt.government.employee.card"/>
 *     &lt;enumeration value="auth.lt.bank"/>
 *     &lt;enumeration value="auth.stork"/>
 *     &lt;enumeration value="auth.tsl.identity.card"/>
 *     &lt;enumeration value="auth.signatureProvider"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "authenticationProvider", namespace = "http://www.epaslaugos.lt/services/authentication")
@XmlEnum
public enum AuthenticationProviderXml {

    @XmlEnumValue("auth.login.pass")
    AUTH_PROVIDER_LOGIN_PASS("auth.login.pass"),
    @XmlEnumValue("auth.lt.identity.card")
    AUTH_PROVIDER_LT_IDENTITY_CARD("auth.lt.identity.card"),
    @XmlEnumValue("auth.lt.government.employee.card")
    AUTH_PROVIDER_LT_EMPLOYEE_CARD("auth.lt.government.employee.card"),
    @XmlEnumValue("auth.lt.bank")
    AUTH_PROVIDER_LT_BANK("auth.lt.bank"),
    @XmlEnumValue("auth.stork")
    AUTH_PROVIDER_STORK("auth.stork"),
    @XmlEnumValue("auth.eidas")
    AUTH_EIDAS("auth.eidas"),
    @XmlEnumValue("auth.tsl.identity.card")
    AUTH_PROVIDER_TSL_IDENTITY_CARD("auth.tsl.identity.card"),
    @XmlEnumValue("auth.signatureProvider")
    AUTH_PROVIDER_SIGNATURE("auth.signatureProvider");
    private final String value;

    AuthenticationProviderXml(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthenticationProviderXml fromValue(String v) {
        for (AuthenticationProviderXml c: AuthenticationProviderXml.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
