//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//


package lt.atea.vaiisis.authentication.model.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticationAttribute.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="authenticationAttribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="lt-personal-code"/>
 *     &lt;enumeration value="lt-company-code"/>
 *     &lt;enumeration value="lt-government-employee-code"/>
 *     &lt;enumeration value="stork-eid"/>
 *     &lt;enumeration value="tsl-serial-number"/>
 *     &lt;enumeration value="login"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "authenticationAttribute", namespace = "http://www.epaslaugos.lt/services/authentication")
@XmlEnum
public enum AuthenticationAttribute {

    @XmlEnumValue("lt-personal-code")
    LT_PERSONAL_CODE("lt-personal-code"),
    @XmlEnumValue("lt-company-code")
    LT_COMPANY_CODE("lt-company-code"),
    @XmlEnumValue("lt-government-employee-code")
    LT_GOVERNMENT_EMPLOYEE_CODE("lt-government-employee-code"),
    @XmlEnumValue("stork-eid")
    STORK_EID("stork-eid"),
    @XmlEnumValue("tsl-serial-number")
    TSL_SERIAL_NUMBER("tsl-serial-number"),
    @XmlEnumValue("login")
    LOGIN("login"),
    @XmlEnumValue("eidas-eid")
    EIDAS_EID("eidas-eid");

    private final String value;

    AuthenticationAttribute(String v) {
        value = v;
    }

    public static AuthenticationAttribute fromValue(String v) {
        for (AuthenticationAttribute c : AuthenticationAttribute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
