//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//


package lt.atea.vaiisis.authentication.model.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for authenticationSourceData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="authenticationSourceData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.epaslaugos.lt/services/authentication}authenticationSourceType"/>
 *         &lt;element name="parameter" type="{http://www.epaslaugos.lt/services/authentication}authenticationSourceParameter" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticationSourceData", namespace = "http://www.epaslaugos.lt/services/authentication", propOrder = {
        "type",
        "parameter"
})
public class AuthenticationSourceData {

    @XmlElement(required = true)
    protected AuthenticationSourceType type;
    @XmlElement(required = true)
    protected List<AuthenticationSourceParameter> parameter;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link AuthenticationSourceType }
     */
    public AuthenticationSourceType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link AuthenticationSourceType }
     */
    public void setType(AuthenticationSourceType value) {
        this.type = value;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticationSourceParameter }
     */
    public List<AuthenticationSourceParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<AuthenticationSourceParameter>();
        }
        return this.parameter;
    }

}
