//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2000/09/xmldsig#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "authentication", namespaceURI = "http://www.epaslaugos.lt/services/authentication"),
		@javax.xml.bind.annotation.XmlNs(prefix = "dsig", namespaceURI = "http://www.w3.org/2000/09/xmldsig#") })
package lt.atea.vaiisis.authentication.model.xml;
