//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//


package lt.atea.vaiisis.authentication.model.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceTarget.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceTarget">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="citizen"/>
 *     &lt;enumeration value="business"/>
 *     &lt;enumeration value="provider"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "serviceTarget", namespace = "http://www.epaslaugos.lt/services/authentication")
@XmlEnum
public enum ServiceTargetXml {

    @XmlEnumValue("citizen")
    SERVICE_TARGET_CITIZEN("citizen"),
    @XmlEnumValue("business")
    SERVICE_TARGET_BUSINESS("business"),
    @XmlEnumValue("provider")
    SERVICE_TARGET_PROVIDER("provider");
    private final String value;

    ServiceTargetXml(String v) {
        value = v;
    }

    public static ServiceTargetXml fromValue(String v) {
        for (ServiceTargetXml c : ServiceTargetXml.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
