//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 01:18:30 PM EET 
//


package lt.atea.vaiisis.authentication.model.xml;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for userInformationPair complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="userInformationPair">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="information" type="{http://www.epaslaugos.lt/services/authentication}userInformation"/>
 *         &lt;element name="value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="stringValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dateValue" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userInformationPair", namespace = "http://www.epaslaugos.lt/services/authentication", propOrder = {
        "information",
        "value"
})
public class UserInformationPair {

    @XmlElement(required = true)
    protected UserInformation information;
    @XmlElement(required = true)
    protected UserInformationPair.Value value;

    /**
     * Gets the value of the information property.
     *
     * @return possible object is
     * {@link UserInformation }
     */
    public UserInformation getInformation() {
        return information;
    }

    /**
     * Sets the value of the information property.
     *
     * @param value allowed object is
     *              {@link UserInformation }
     */
    public void setInformation(UserInformation value) {
        this.information = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link UserInformationPair.Value }
     */
    public UserInformationPair.Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link UserInformationPair.Value }
     */
    public void setValue(UserInformationPair.Value value) {
        this.value = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="stringValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dateValue" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "stringValue",
            "dateValue"
    })
    public static class Value {

        @XmlElement(namespace = "http://www.epaslaugos.lt/services/authentication")
        protected String stringValue;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/authentication")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateValue;

        /**
         * Gets the value of the stringValue property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getStringValue() {
            return stringValue;
        }

        /**
         * Sets the value of the stringValue property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setStringValue(String value) {
            this.stringValue = value;
        }

        /**
         * Gets the value of the dateValue property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDateValue() {
            return dateValue;
        }

        /**
         * Sets the value of the dateValue property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDateValue(XMLGregorianCalendar value) {
            this.dateValue = value;
        }

    }

}
