name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-evartai:
    name: Build viisp-auth-helper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
